08 refatorar classe controllers
DiogoNo/Mkt pull request #11
Opened 2023-04-27 01:36 UTC by LuisFAraujo

2023-04-27 13:59 UTC, DiogoNo requested changes

2023-04-27 13:59 UTC, DiogoNo commented on server/controllers/product.js
> +    console.log("aqui")
Tirar o console.log

```suggestion
   
```

2023-04-27 13:59 UTC, DiogoNo commented on server/validators/product/productValidation.js
> +    console.log(validations)
Tirar o console.log

```suggestion
   
```

2023-04-27 13:59 UTC, DiogoNo commented on server/validators/product/productValidation.js
> +    const { name,description,price,category,quantity,shipping,photo } = fields;
Esta faltando o eslint configurado

```suggestion
    const { name, description, price, category, quantity, shipping, photo } = fields;
```

2023-04-27 13:59 UTC, DiogoNo commented on server/controllers/product.js
> +    const error = await validateCreate({name,description,price,category,quantity,shipping,photo})
Faltando a validacao do eslint 

```suggestion
    const error = await validateCreate({name, description, price, category, quantity, shipping, photo})
```

2023-04-27 13:59 UTC, DiogoNo commented on server/controllers/category.js
> +        if (error.length > 0) {
```suggestion
        if (error.length) {
```

poderia testar sem a condicao do > 0, acredito que quando ele não tiver erro no array o length do array vai se comportar como 0 que eh igual a falso no boolean

2023-04-27 15:46 UTC, Andre-Vinicius22 commented
Acredito que dentro da pasta validators não seja necessário as subpastas para cada arquivo

2023-05-04 23:00 UTC, DiogoNo commented on server/utils/emailValidator.js
> +const emailRegex =  /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
uma sugestão é criar uma pasta util, aonde armazenaria essas constantes, pois possa ser reutilizada em outro lugar, seria legal um arquivo que armazenaria const regex?

2023-05-04 23:05 UTC, DiogoNo commented on server/validators/product/productValidation.js
> +      () => !(photo && photo.size > MAX_FILE_SIZE_MB * 1024 * 1024) && "Invalid image size",
uma sugestão é criar um function no util para esse calculo dessse temanho do mb, por exemplo que retornaria a mutiplicação do *1024 *1024

2023-06-16 18:19 UTC, closed without merging